---
title: "Checklists"
---

# Enrollment and Admission

-   "Application for admission to doctoral procedures in the Department of Biology"
-   "Confirmation of academic supervision"/"Betreuungsvereinbarung"
-   "Description of the topic and outline of the research project"
-   Master degree certificate
-   Master Transcript of Records
-   Bachelor degree certificate
-   Bachelor Transcript of Records
-   A-level certificate
-   copy of your ID/passport
-   CV

All these documents have to handed in as one PDF document!

If you have a supervisor who is not working at the University of Hamburg you also have to submit a "Application for the right to examine"/"Antrag auf Prüfungsrecht" for your supervisor which needs to have the following within one PDF:

-   CV of your supervisor
-   List of supervised theses
-   List of publications from your supervisor
-   certificate of being a professor at a University

Application websites:

-   Enrollment: Stine <https://www.stine.uni-hamburg.de/>
-   Admission: Docata <https://www.promovieren.uni-hamburg.de/en/min/promotion/voraussetzungen.html>

# Travelling

Before the travel

-   roughly calculate the potential costs of the trip
-   check how much the university will pay for accommodation and daily allowance in the country to which you travel
-   fill out the travel request form (if the total costs will be higher than 200€ don´t forget to apply for advanced payment)
-   after your travel got accepted apply for the A1 certificate (if you are travelling outside of Germany)

During travelling

-   save receipts of public transportation, taxi / uber etc. (if you don´t get one but paid with a credit card you can also validate your costs by showing your banking statements)
-   if you don´t get the daily allowance save all other receipts too (e.g. from supermarkets, restaurants) to get reimbursed for your living costs

After the travel

-   fill out the travel expense form (if you got an advanced payment you have to hand in the form **6 weeks** after you came back from the business trip)

-   Attach all necessary documents to show how much many you spend, this includes e.g.:

    -   flight tickets

    -   hotel receipts

    -   public transportation

    -   living costs

    -   program or agenda of the meeting / conference

# Hiwi contracts

Information that Laura needs to set up the contracts:

-   full name of your planned HiWi person

-   mobile phone number + E-Mail address of your planned HiWi person

-   duration of the contract: from xx.xx.xxxx to xx.xx.xxxx

-   PSP/WBS element (the money pot)

-   working hours per month

# Visa for international students

-   Letter of acceptance 

-   Working contract from the University of Hamburg or other funding sources

-   Health insurance (TK, AOK, DAK, other public insurances)

-   Other documents (bachelor certificate, passport, accommodation)

-   residence permit

-   register housing

# Purchasing
