---
title: "Enrollment as PhD"
---

**Immatriculation/Enrollment as PhD Student**

Although you have a working contract with the University you also have to immatriculate at the University as PhD Student (and therefore also have to pay semester fees) via Stine (<https://www.stine.uni-hamburg.de/>). Additionally you have to apply for admission of your PhD via Docata (<https://docata.min.uni-hamburg.de/home>). You will need to fill out several forms and send several information to the biology department bureau, Mrs. Ziemer is the go-to person for PhD students. On these websites you can find further and detailed information:

-   Enrollment: <https://www.promovieren.uni-hamburg.de/en/min/promotion/einschreibung.html>

-   Admission: <https://www.promovieren.uni-hamburg.de/en/min/promotion/zulassung.html>

You can find a checklist with all the documents [here](checklists.qmd).

You are then enrolled as a PhD student for the next 4 years. If you need an expansion you have to write Mrs. Ziemer at least 3 months before these 4 years end.

\
