---
title: "Hiwi contracts"
---

**HiWi contracts**

If you want/need to employ a HiWi there is also some helpful information how to organize that:

Because the HR office needs to set up the HiWi contract you need to plan ahead. The current deadlines for HiWi contracts are 6 weeks before the planned start of the contract. During vacation time the deadline can expand to 8 weeks before the start of the contract. (Laura knows the most current deadline)

Laura needs the following information from you to send to the HR office for the contract:

-   full name of your planned HiWi person

-   mobile phone number + E-Mail address of your planned HiWi person

-   duration of the contract: from xx.xx.xxxx to xx.xx.xxxx

-   PSP/WBS element (the money pot)

-   how many working hours the HiWi will get in the contract. There are 2 possibilities for HiWi contracts: full contracts and half contracts. Which one you choose depends on how much work you need/want to be done by your HiWi and also how much you can spend on HiWis (ask your supervisor or the person in charge of your money pot). A half contract means 41-43 working hours per month. A full contract means 83-86 working hours per month. If it is the lower or the higher amount of working hours depends on the health insurance of your planned HiWi person (still health insured via family insurance or insured by himself/herself/themselves). Because different health insurance situations allow different amounts of earned money by the insured person.

After you send the information to Laura she will contact your planned HiWi person (and supervisor/person in charge of your money pot) and will organize everything else needed for the contract.

When your HiWi then finally starts working you are the person responsible for your HiWi, which means you have to make sure that he/she/they gets a safety briefing if needed and your HiWi is not the only person in the building while working (especially if it is a bachelor student). Therefore you shall always know when your HiWi is in the institute's buildings for working. In none of our current buildings is something like a system to log in and out when you come and go for work, therefore there is no real control when and for how long your HiWi works and if the HiWi really works the amount of hours that you pay for. Hence it is recommended that you set up a broad working schedule/plan with your HiWi (e.g. the HiWi writes you at which days from when to when he/she/they plan to work in the upcoming weeks etc.) or ask them to write down the hours in a shared Excel Document etc.

\
