---
title: "International students"
---

**Getting started in Germany as an international PhD student**

First of all, you must be aware that your countries are eligible to enter Germany by checking out the Staatenliste zur Visumpflicht ([Overview of visa requirements/exemptions for entry into the Federal Republic of Germany - Federal Foreign Office (auswaertiges-amt.de)](https://www.auswaertiges-amt.de/en/visa-service/-/231148).

Several documents are needed to apply for a working visa. You will need to apply for a visa for research in accordance with Section 18 on the Residence Act - AufenthG. You are considered a "researcher" if you have at least a PhD/doctorate or a suitable university degree enabling you to access PhD degree programmes (Article 3 of Directive (EU) 2016/801). There are several documents are needed:

1.  Letter of acceptance, 

2.  Working contract from the University of Hamburg or other funding sources,

3.  Health insurance (TK, AOK, DAK, other public insurances),

4.  Other documents (bachelor certificate, passport, accommodation).

In addition, after you arrive in Germany, you must apply for a residence permit and register your house/ apartment in the city hall (Rathaus). After 3 years (depending on your PhD contract), if you have yet graduated, you have to extend your residence permit.

Also, you also can visit the "Welcome Service für Internationale Forschende" from the University of Hamburg website to get several insights for living in Hamburg for the internationals.

\
